@hostname = lagare.local
@port = 3000
@host = http://{{hostname}}:{{port}}/api
@authToken = {{login.response.body.token}}
@id = {{create.response.body.data.id}}


# @name login
POST {{host}}/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

&email=sudo@teda.id.au
&password=password123


### Create (POST)
# @name create
POST {{host}}/reset-tokens HTTP/1.1
Authorization: Bearer {{authToken}}
content-type: application/x-www-form-urlencoded

&email=user@teda.id.au


### Read (GET)
GET {{host}}/reset-tokens HTTP/1.1
Authorization: Bearer {{authToken}}


### Read (GET/:id)
GET {{host}}/reset-tokens/{{id}} HTTP/1.1
Authorization: Bearer {{authToken}}


### Update (PUT/:id)
PUT {{host}}/reset-tokens/{{id}} HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/x-www-form-urlencoded

&email=Bill.Bob@hotmail.com


### Update (PUT/:id)
PUT {{host}}/reset-tokens/{{id}} HTTP/1.1
Authorization: Bearer {{authToken}}
Content-Type: application/x-www-form-urlencoded

&isUsed=true


### Delete (DELETE/:id)
DELETE {{host}}/reset-tokens/{{id}} HTTP/1.1
Authorization: Bearer {{authToken}}


### Delete All (DELETE)
DELETE {{host}}/reset-tokens HTTP/1.1
Authorization: Bearer {{authToken}}
