@authToken = {{login.response.body.token}}

# @name login
POST https://lagare.local:8000/api/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

&email=ian@teda.id.au
&password=password123


### Create Thing
POST https://lagare.local:8000/api/things
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{authToken}}

&name=Thingiemabobddd 
&description=Thingie ma bob
&price=0.99


### Read things
GET https://lagare.local:8000/api/things
Authorization: Bearer {{authToken}}


### Read things
GET https://lagare.local:8000/api/things/22
Authorization: Bearer {{authToken}}


### Update Thing
PUT https://lagare.local:8000/api/things/22
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{authToken}}

name=Updated Thing
&description=Updated thing description
&price=99.99


### Delete thing
DELETE https://lagare.local:8000/api/things/22
Authorization: Bearer {{authToken}}


### 404
GET https://lagare.local:8000/api/none-route
Authorization: Bearer {{authToken}}


### Create Thing Errors
POST https://lagare.local:8000/api/things
Authorization: Bearer {{authToken}}

// https://github.com/Huachao/vscode-restclient