@hostname = lagare.local
@port = 3000
@host = http://{{hostname}}:{{port}}/api
@authToken = {{login.response.body.token}}
@id = {{create.response.body.data.id}}

### Login to api
# @name login
POST {{host}}/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

&email=sudo@teda.id.au
&password=password123


### Create Thing
# @name create
POST {{host}}/things
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{authToken}}

&name=Thingiemabobddd 
&description=Thingie ma bob
&price=0.99


### Read things
GET {{host}}/things
Authorization: Bearer {{authToken}}


### Read things
GET {{host}}/things/{{id}}
Authorization: Bearer {{authToken}}


### Update Thing
PUT {{host}}/things/{{id}}
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{authToken}}

&name=Updated Thing
&description=Updated thing description
&price=99.99


### Delete thing
DELETE {{host}}/things/{{id}}
Authorization: Bearer {{authToken}}


### 404
GET {{host}}/none-route
Authorization: Bearer {{authToken}}


### Create Thing Errors
POST {{host}}/things
Authorization: Bearer {{authToken}}

// https://github.com/Huachao/vscode-restclient
