@hostname = lagare.local
@port = 3000
@host = http://{{hostname}}:{{port}}/api
@authToken = {{login.response.body.token}}
@id = {{create.response.body.data.id}}
@me = {{login.request.body.user.id}}

### Login to api
# @name login
POST {{host}}/login HTTP/1.1
Content-Type: application/x-www-form-urlencoded

&email=admin@teda.id.au
&password=password123


### Create User
# @name create
POST {{host}}/users
content-type: application/x-www-form-urlencoded
Authorization: Bearer {{authToken}}

&firstName=Thingie
&lastName=Bobb
&email=someone@hotmail.com
&password=password123
&status=inactive

### Read Users
GET {{host}}/users
Authorization: Bearer {{authToken}}


### Read User
GET {{host}}/users/{{id}}
Authorization: Bearer {{authToken}}



### Read User User
GET {{host}}/users/1
Authorization: Bearer {{authToken}}


### Update User
PUT {{host}}/users/{{id}}
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{authToken}}

&status=active

### Delete User
DELETE {{host}}/users/{{id}}
Authorization: Bearer {{authToken}}


### Delete User User
DELETE {{host}}/users/1
Authorization: Bearer {{authToken}}


### Create Users Errors
POST {{host}}/users
Authorization: Bearer {{authToken}}

// https://github.com/Huachao/vscode-restclient
